//Get Feedback
export const GET_SUMMERY = 'GET_SUMMERY';
export const GET_SUMMERY_SUCCESS = 'GET_SUMMERY_SUCCESS';
export const GET_SUMMERY_ERROR = 'GET_SUMMERY_ERROR';

export const GET_FEEDBACK = 'GET_FEEDBACK';
export const GET_FEEDBACK_SUCCESS = 'GET_FEEDBACK_SUCCESS';
export const GET_FEEDBACK_ERROR = 'GET_FEEDBACK_ERROR';

export const FEEDBACK_SEARCH = 'FEEDBACK_SEARCH';
export const FEEDBACK_SEARCH_SUCCESS = 'FEEDBACK_SEARCH_SUCCESS';
export const FEEDBACK_SEARCH_ERROR = 'FEEDBACK_SEARCH_ERROR';

export const REPLY = 'REPLY';
export const REPLY_SUCCESS = 'REPLY_SUCCESS';
export const REPLY_ERROR = 'REPLY_ERROR';